//
//  FailureRequestActorStorage.swift
//  Networking
//
//  Created by Fazliddinov Iskandar on 26/05/25.
//

import Foundation
import NetworkProtocols


public actor DefaultFailureRequestActorStorage: ContinuableFailureRequestStorageProtocol {
    
    private var isDebug: Bool
    
    public init(isDebug: Bool = false) {
        self.isDebug = isDebug
    }
    
    private struct DeferredRequest {
        let operation: @Sendable () async throws -> Void
        let continuation: CheckedContinuation<Void, Error>?
    }
    
    private var pendingRequests: [DeferredRequest] = []
    
    public func pending() async -> [@Sendable () async throws -> Void] {
        safePrint(isDebug: self.isDebug, "üìã –ü–æ–ª—É—á–µ–Ω–∏–µ —Å–ø–∏—Å–∫–∞ –æ—Ç–ª–æ–∂–µ–Ω–Ω—ã—Ö –∑–∞–ø—Ä–æ—Å–æ–≤, –≤—Å–µ–≥–æ: \(pendingRequests.count)")
        return pendingRequests.map { $0.operation }
    }

    public func add<E: Endpoint>(
            _ request: E,
            using client: AsyncRequestExecuteProtocol
        ) async {
            await add(request, using: client, continuation: nil)
        }

        // –ù–æ–≤—ã–π –º–µ—Ç–æ–¥ ‚Äî —Å continuation
        public func add<E: Endpoint>(
            _ request: E,
            using client: AsyncRequestExecuteProtocol,
            continuation: CheckedContinuation<E.Response, Error>? = nil
        ) async {
            safePrint(isDebug: self.isDebug, "‚ûï –î–æ–±–∞–≤–ª—è–µ–º –Ω–æ–≤—ã–π –æ—Ç–ª–æ–∂–µ–Ω–Ω—ã–π –∑–∞–ø—Ä–æ—Å —Å id: \(request.id)")

            let operation: @Sendable () async throws -> Void = {
                await safePrint(isDebug: self.isDebug, "‚ñ∂Ô∏è –í—ã–ø–æ–ª–Ω—è–µ–º –æ—Ç–ª–æ–∂–µ–Ω–Ω—ã–π –∑–∞–ø—Ä–æ—Å —Å id: \(request.id)")
                do {
                    let response = try await client.execute(request)
                    await safePrint(isDebug: self.isDebug, "‚úÖ –£—Å–ø–µ—à–Ω–æ –≤—ã–ø–æ–ª–Ω–µ–Ω –æ—Ç–ª–æ–∂–µ–Ω–Ω—ã–π –∑–∞–ø—Ä–æ—Å —Å id: \(request.id)")
                    continuation?.resume(returning: response)
                } catch {
                    await safePrint(isDebug: self.isDebug, "‚ùå –û—à–∏–±–∫–∞ –ø—Ä–∏ –ø–æ–≤—Ç–æ—Ä–µ –∑–∞–ø—Ä–æ—Å–∞: \(error)")
                    continuation?.resume(throwing: error)
                }
            }

            pendingRequests.append(.init(operation: operation, continuation: nil))
        }

    public func retryAll() async {
        let tasks = pendingRequests
        pendingRequests.removeAll()
        safePrint(isDebug: self.isDebug, "üîÑ –ó–∞–ø—É—Å–∫–∞–µ–º –ø–æ–≤—Ç–æ—Ä –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è \(tasks.count) –æ—Ç–ª–æ–∂–µ–Ω–Ω—ã—Ö –∑–∞–ø—Ä–æ—Å–æ–≤...")

        for task in tasks {
            do {
                try await task.operation()
            } catch {
                safePrint(isDebug: self.isDebug, "‚ùå –û—à–∏–±–∫–∞ –ø—Ä–∏ –ø–æ–≤—Ç–æ—Ä–µ –∑–∞–ø—Ä–æ—Å–∞: \(error)")
            }
        }

        safePrint(isDebug: self.isDebug, "üéâ –í—Å–µ –æ—Ç–ª–æ–∂–µ–Ω–Ω—ã–µ –∑–∞–ø—Ä–æ—Å—ã –æ–±—Ä–∞–±–æ—Ç–∞–Ω—ã")
    }
}
